server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_userService
    username: root
    password: kabeer@9930
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

      
      
        